#   ██████╗  ██████╗ ██████╗ ███████╗██╗    ██╗██╗ ██████╗ ███╗   ██╗
#  ██╔════╝ ██╔═══██╗██╔══██╗██╔════╝ ██║  ██╔╝██║██╔═══██╗████╗  ██║
#  ██║      ██║   ██║██║  ██║█████╗    █████╔╝ ██║██║   ██║██╔██╗ ██║
#  ██║      ██║   ██║██║  ██║██╔══╝   ██╔═ ██╗ ██║██║   ██║██║╚██╗██║
#  ╚██████╗ ╚██████╔╝██████╔╝███████╗██║    ██╗██║╚██████╔╝██║ ╚████║
#   ╚═════╝  ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝

NAME		= codexion
NAME_BONUS 	= codexion_bonus

CC			= cc
CFLAGS 		= -Wall -Werror -Wextra -pthread
RM			= rm -rf

SRCS 		= coders/main.c \
			= coders/parsing.c \
			= coders/utils.c

OBJS		= $(SRCS:.c=.o)

SRCS_BONUS	= coders/main_bonus.c \
			= coders/parsing_bonus.c \
			= coders/utils_bonus.c

# Colors
DEF_COLOR   = \033[0;39m
GRAY        = \033[0;90m
GREEN       = \033[0;92m

OBJS_BONUS	= $(SRCS:.c=.o)

all: $(NAME)

# target : dependencies
#	command
$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
	@echo "$(GREEN)Codexion compiled successfuly!$(DEF_COLOR)"

bonus: $(NAME_BONUS)

$(NAME_BONUS): $(OBJS_BONUS)
	$(CC) $(CFLAGS) $(OBJS_BONUS) -o $(NAME_BONUS)
	@echo "$(GREEN)Codexion Bonus compiled successflly!$(DEF_COLOR)"

%o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS) $(OBJS_BONUS)
	@echo "$(GRAY)Deleted objects.$(DEF_COLOR)"

fclean: clean
	$(RM) $(OBJS) $(OBJS_BONUS)
	@echo "$(GRAY)Deleted Executables.$(DEF_COLOR)"

re: fclean all

.PHONY: all clean fclean re bonus

